default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["SUPABASE_DB_HOST"] %>
  database: <%= ENV["SUPABASE_DB_NAME"] %>
  username: <%= ENV["SUPABASE_DB_USER"] %>
  password: <%= ENV["SUPABASE_DB_PASSWORD"] %>
  port: <%= ENV.fetch("SUPABASE_DB_PORT") { 5432 } %>
  sslmode: require
  prepared_statements: false

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("SUPABASE_DB_NAME", "gauger") %>_test

production:
  <<: *default
